index:
    path: /
    controller: App\Controller\HomepageController::html

admin:
    # admin-only!
    path: /admin
    controller: App\Controller\AdminController::html

login:
    path: /anmelden
    controller: App\Controller\LoginController::html

app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\LoginController::login

blogentry-list:
    # admin-only!
    path: /blogeintraege-verwalten
    controller: App\Controller\BlogEntryListController::html

blogentry-new:
    # admin-only!
    path: /neuer-eintrag
    controller: App\Controller\NewBlogEntryController::html

reset-password:
    path: /passwort-vergessen
    controller: App\Controller\ResetPasswordController::html

register:
    path: /registrieren
    controller: App\Controller\RegisterController::html

search:
    path: /s={search}
    controller: App\Controller\SearchController::html